version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.controller.api_controller:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: unless-stopped
